<a href="https://colab.research.google.com/github/ShradhaPai/Zomato-Restaurant-Analysis/blob/main/Zomato.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("data.xlsx")
print(df.head(10))

   Restaurant ID              Restaurant Name  Country Code       City  \
0        7402935                         Skye            94    Jakarta
1        7410290     Satoo - Hotel Shangri-La            94    Jakarta
2        7420899                   Sushi Masa            94    Jakarta
3        7421967               3 Wise Monkeys            94    Jakarta
4        7422489  Avec Moi Restaurant and Bar            94    Jakarta
5       18352452   Lucky Cat Coffee & Kitchen            94    Jakarta
6       18386856                      Onokabe            94  Tangerang
7        7423482                   Lemongrass            94      Bogor
8       18391256                        MONKS            94    Jakarta
9        7422633             Talaga Sampireun            94    Jakarta

                                             Address  \
0  Menara BCA, Lantai 56, Jl. MH. Thamrin, Thamri...
1               Hotel Shangri-La, Jl. Jend. Sudirman
2                   Jl. Tuna Raya No. 5, Penjaringan
3                Jl. Suryo No. 26, Senopati, Jakarta
4  Gedung PIC, Jl. Teluk Betung 43, Thamrin, Jakarta
5  Plaza Festival, South Parking, Jl. HR Rasuna S...
6  Alam Sutera Town Center, Jl. Alam Utama, Serpo...
7      Jl. Raya Pajajaran No. 21, Bogor Utara, Bogor
8  Komplek Graha Boulevard Timur, Summarecon Kela...
9                             Jl. Lingkar Luar Barat

                                 Locality  \
0           Grand Indonesia Mall, Thamrin
1              Hotel Shangri-La, Sudirman
2                             Penjaringan
3                                Senopati
4                                 Thamrin
5                Plaza Festival, Kuningan
6  Alam Sutera Town Center, Serpong Utara
7                             Bogor Utara
8                           Kelapa Gading
9                              Cengkareng

                                    Locality Verbose   Longitude  Latitude  \
0             Grand Indonesia Mall, Thamrin, Jakarta  106.821999 -6.196778
1                Hotel Shangri-La, Sudirman, Jakarta  106.818961 -6.203292
2                               Penjaringan, Jakarta  106.800144 -6.101298
3                                  Senopati, Jakarta  106.813400 -6.235241
4                                   Thamrin, Jakarta  106.821023 -6.196270
5                  Plaza Festival, Kuningan, Jakarta  106.831748 -6.218932
6  Alam Sutera Town Center, Serpong Utara, Tangerang  106.652688 -6.241792
7                                 Bogor Utara, Bogor  106.807850 -6.576578
8                             Kelapa Gading, Jakarta  106.911335 -6.163948
9                                Cengkareng, Jakarta  106.728508 -6.168467

                     Cuisines  Average Cost for two                Currency  \
0        Italian, Continental                800000  Indonesian Rupiah(IDR)
1  Asian, Indonesian, Western                800000  Indonesian Rupiah(IDR)
2             Sushi, Japanese                500000  Indonesian Rupiah(IDR)
3                    Japanese                450000  Indonesian Rupiah(IDR)
4             French, Western                350000  Indonesian Rupiah(IDR)
5               Cafe, Western                300000  Indonesian Rupiah(IDR)
6                  Indonesian                300000  Indonesian Rupiah(IDR)
7       Peranakan, Indonesian                250000  Indonesian Rupiah(IDR)
8        Western, Asian, Cafe                250000  Indonesian Rupiah(IDR)
9           Sunda, Indonesian                200000  Indonesian Rupiah(IDR)

  Has Table booking Has Online delivery  Price range  Aggregate rating  \
0                No                  No            3               4.1
1                No                  No            3               4.6
2                No                  No            3               4.9
3                No                  No            3               4.2
4                No                  No            3               4.3
5                No                  No            3               4.3
6                No                  No            3               3.7
7                No                  No            3               4.0
8                No                  No            3               4.2
9                No                  No            3               4.9

  Rating color Rating text  Votes
0        Green   Very Good   1498
1   Dark Green   Excellent    873
2   Dark Green   Excellent    605
3        Green   Very Good    395
4        Green   Very Good    243
5        Green   Very Good    458
6       Yellow        Good    155
7        Green   Very Good   1159
8        Green   Very Good    259
9   Dark Green   Excellent   1662

In [ ]:
print(df.columns)

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating',
       'Rating color', 'Rating text', 'Votes'],
      dtype='object')

In [ ]:
for i in range(1,36):
  # print(f"Q{i}_Pre, Q{i}_Post", end = ",")
  print("Q",i,"_Pre,Q",i,"_Post", end = ",",sep = "")

Q1_Pre,Q1_Post,Q2_Pre,Q2_Post,Q3_Pre,Q3_Post,Q4_Pre,Q4_Post,Q5_Pre,Q5_Post,Q6_Pre,Q6_Post,Q7_Pre,Q7_Post,Q8_Pre,Q8_Post,Q9_Pre,Q9_Post,Q10_Pre,Q10_Post,Q11_Pre,Q11_Post,Q12_Pre,Q12_Post,Q13_Pre,Q13_Post,Q14_Pre,Q14_Post,Q15_Pre,Q15_Post,Q16_Pre,Q16_Post,Q17_Pre,Q17_Post,Q18_Pre,Q18_Post,Q19_Pre,Q19_Post,Q20_Pre,Q20_Post,Q21_Pre,Q21_Post,Q22_Pre,Q22_Post,Q23_Pre,Q23_Post,Q24_Pre,Q24_Post,Q25_Pre,Q25_Post,Q26_Pre,Q26_Post,Q27_Pre,Q27_Post,Q28_Pre,Q28_Post,Q29_Pre,Q29_Post,Q30_Pre,Q30_Post,Q31_Pre,Q31_Post,Q32_Pre,Q32_Post,Q33_Pre,Q33_Post,Q34_Pre,Q34_Post,Q35_Pre,Q35_Post,

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9550 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Price range           9551 non-null   int64
 15  Aggregate rating      9551 non-null   float64
 16  Rating color          9551 non-null   object
 17  Rating text           9551 non-null   object
 18  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(11)
memory usage: 1.4+ MB
None

In [ ]:
print(df.describe())

       Restaurant ID  Country Code    Longitude     Latitude  \
count   9.551000e+03   9551.000000  9551.000000  9551.000000
mean    9.051128e+06     18.365616    64.126574    25.854381
std     8.791521e+06     56.750546    41.467058    11.007935
min     5.300000e+01      1.000000  -157.948486   -41.330428
25%     3.019625e+05      1.000000    77.081343    28.478713
50%     6.004089e+06      1.000000    77.191964    28.570469
75%     1.835229e+07      1.000000    77.282006    28.642758
max     1.850065e+07    216.000000   174.832089    55.976980

       Average Cost for two  Price range  Aggregate rating         Votes
count           9551.000000  9551.000000       9551.000000   9551.000000
mean            1199.210763     1.804837          2.666370    156.909748
std            16121.183073     0.905609          1.516378    430.169145
min                0.000000     1.000000          0.000000      0.000000
25%              250.000000     1.000000          2.500000      5.000000
50%              400.000000     2.000000          3.200000     31.000000
75%              700.000000     2.000000          3.700000    131.000000
max           800000.000000     4.000000          4.900000  10934.000000

In [ ]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         1
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
df.dropna(subset = ["Restaurant Name"])

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Aggregate rating,Rating color,Rating text,Votes
0,7402935,Skye,94,Jakarta,"Menara BCA, Lantai 56, Jl. MH. Thamrin, Thamri...","Grand Indonesia Mall, Thamrin","Grand Indonesia Mall, Thamrin, Jakarta",106.821999,-6.196778,"Italian, Continental",800000,Indonesian Rupiah(IDR),No,No,3,4.1,Green,Very Good,1498
1,7410290,Satoo - Hotel Shangri-La,94,Jakarta,"Hotel Shangri-La, Jl. Jend. Sudirman","Hotel Shangri-La, Sudirman","Hotel Shangri-La, Sudirman, Jakarta",106.818961,-6.203292,"Asian, Indonesian, Western",800000,Indonesian Rupiah(IDR),No,No,3,4.6,Dark Green,Excellent,873
2,7420899,Sushi Masa,94,Jakarta,"Jl. Tuna Raya No. 5, Penjaringan",Penjaringan,"Penjaringan, Jakarta",106.800144,-6.101298,"Sushi, Japanese",500000,Indonesian Rupiah(IDR),No,No,3,4.9,Dark Green,Excellent,605
3,7421967,3 Wise Monkeys,94,Jakarta,"Jl. Suryo No. 26, Senopati, Jakarta",Senopati,"Senopati, Jakarta",106.813400,-6.235241,Japanese,450000,Indonesian Rupiah(IDR),No,No,3,4.2,Green,Very Good,395
4,7422489,Avec Moi Restaurant and Bar,94,Jakarta,"Gedung PIC, Jl. Teluk Betung 43, Thamrin, Jakarta",Thamrin,"Thamrin, Jakarta",106.821023,-6.196270,"French, Western",350000,Indonesian Rupiah(IDR),No,No,3,4.3,Green,Very Good,243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,18279289,BMG - All Day Dining,1,Dehradun,"140 A, Rajpur Road, Jakhan, Dehradun",Jakhan,"Jakhan, Dehradun",78.068890,30.362686,"Chinese, North Indian, Fast Food",0,Indian Rupees(Rs.),No,No,1,4.3,Green,Very Good,63
9547,2300497,Atmosphere Grill Cafe Sheesha,1,Kanpur,"8th Floor, J.S. Tower, 16/106 - Mall Road, Kan...",Mall Road,"Mall Road, Kanpur",80.354002,26.472001,"Indian, Chinese, Continental",0,Indian Rupees(Rs.),No,No,1,3.6,Yellow,Good,34
9548,18312106,UrbanCrave,1,Kanpur,"14/125, The Mall, Mall Road, Colonelganj, Para...",Parade,"Parade, Kanpur",80.342796,26.474986,"Cafe, Continental, Desserts, Ice Cream, Italia...",0,Indian Rupees(Rs.),No,No,1,3.9,Yellow,Good,127
9549,3900245,Deena Chat Bhandar,1,Varanasi,"D-47/184, Luxa Road, Dashaswmedh Road, Varanasi",Dashaswmedh Road,"Dashaswmedh Road, Varanasi",0.000000,0.000000,Street Food,0,Indian Rupees(Rs.),No,No,1,3.8,Yellow,Good,78
9550,18246202,VNS Live Studio,1,Varanasi,"Hotel Varuna Ground Floor, 22 Gulab Bagh, Sigr...",Sigra,"Sigra, Varanasi",82.991694,25.318345,"Chinese, North Indian",0,Indian Rupees(Rs.),No,No,1,3.5,Yellow,Good,109

In [ ]:
df.dropna(subset = ["Cuisines"])

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Price range,Aggregate rating,Rating color,Rating text,Votes
0,7402935,Skye,94,Jakarta,"Menara BCA, Lantai 56, Jl. MH. Thamrin, Thamri...","Grand Indonesia Mall, Thamrin","Grand Indonesia Mall, Thamrin, Jakarta",106.821999,-6.196778,"Italian, Continental",800000,Indonesian Rupiah(IDR),No,No,3,4.1,Green,Very Good,1498
1,7410290,Satoo - Hotel Shangri-La,94,Jakarta,"Hotel Shangri-La, Jl. Jend. Sudirman","Hotel Shangri-La, Sudirman","Hotel Shangri-La, Sudirman, Jakarta",106.818961,-6.203292,"Asian, Indonesian, Western",800000,Indonesian Rupiah(IDR),No,No,3,4.6,Dark Green,Excellent,873
2,7420899,Sushi Masa,94,Jakarta,"Jl. Tuna Raya No. 5, Penjaringan",Penjaringan,"Penjaringan, Jakarta",106.800144,-6.101298,"Sushi, Japanese",500000,Indonesian Rupiah(IDR),No,No,3,4.9,Dark Green,Excellent,605
3,7421967,3 Wise Monkeys,94,Jakarta,"Jl. Suryo No. 26, Senopati, Jakarta",Senopati,"Senopati, Jakarta",106.813400,-6.235241,Japanese,450000,Indonesian Rupiah(IDR),No,No,3,4.2,Green,Very Good,395
4,7422489,Avec Moi Restaurant and Bar,94,Jakarta,"Gedung PIC, Jl. Teluk Betung 43, Thamrin, Jakarta",Thamrin,"Thamrin, Jakarta",106.821023,-6.196270,"French, Western",350000,Indonesian Rupiah(IDR),No,No,3,4.3,Green,Very Good,243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,18279289,BMG - All Day Dining,1,Dehradun,"140 A, Rajpur Road, Jakhan, Dehradun",Jakhan,"Jakhan, Dehradun",78.068890,30.362686,"Chinese, North Indian, Fast Food",0,Indian Rupees(Rs.),No,No,1,4.3,Green,Very Good,63
9547,2300497,Atmosphere Grill Cafe Sheesha,1,Kanpur,"8th Floor, J.S. Tower, 16/106 - Mall Road, Kan...",Mall Road,"Mall Road, Kanpur",80.354002,26.472001,"Indian, Chinese, Continental",0,Indian Rupees(Rs.),No,No,1,3.6,Yellow,Good,34
9548,18312106,UrbanCrave,1,Kanpur,"14/125, The Mall, Mall Road, Colonelganj, Para...",Parade,"Parade, Kanpur",80.342796,26.474986,"Cafe, Continental, Desserts, Ice Cream, Italia...",0,Indian Rupees(Rs.),No,No,1,3.9,Yellow,Good,127
9549,3900245,Deena Chat Bhandar,1,Varanasi,"D-47/184, Luxa Road, Dashaswmedh Road, Varanasi",Dashaswmedh Road,"Dashaswmedh Road, Varanasi",0.000000,0.000000,Street Food,0,Indian Rupees(Rs.),No,No,1,3.8,Yellow,Good,78
9550,18246202,VNS Live Studio,1,Varanasi,"Hotel Varuna Ground Floor, 22 Gulab Bagh, Sigr...",Sigra,"Sigra, Varanasi",82.991694,25.318345,"Chinese, North Indian",0,Indian Rupees(Rs.),No,No,1,3.5,Yellow,Good,109

In [ ]:
# Top 10 cities with most restaurants
df["City"].value_counts().head(10)

City
New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Ahmedabad         21
Amritsar          21
Bhubaneshwar      21
Guwahati          21
Lucknow           21
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Cities with least resataurants
df["City"].value_counts(ascending=True)

City
Bandung             1
Panchkula           1
Mohali              1
Quezon City         1
Tagaytay City       1
                 ...
Ghaziabad          25
Faridabad         251
Noida            1080
Gurgaon          1118
New Delhi        5473
Name: count, Length: 141, dtype: int64

In [ ]:
# City with least restaurant
df["City"].value_counts().idxmin()

'Bandung'

In [ ]:
# Restaurants with many franchise
df.groupby("Restaurant Name")["City"].nunique().sort_values(ascending = False)

Restaurant Name
Barbeque Nation               22
Pizza Hut                     12
KFC                            8
The Yellow Chilli              7
Domino's Pizza                 7
                              ..
Fu.D                           1
Fry Centre                     1
Fruitpro                       1
Frugurpop-  ibis New Delhi     1
Funk House Cafe                1
Name: City, Length: 7445, dtype: int64

In [ ]:
# Ratio of restaurants having table booking vs no table booking
ratio = df["Has Table booking"].value_counts().get("Yes", 0) / df["Has Table booking"].value_counts().get("No", 1)
print("Table booking ratio(Yes/No):", ratio)

Table booking ratio(Yes/No): 0.13797211962349576

In [ ]:
# Percentage of restaurants providing online delivery
percentage = (df['Has Online delivery'].value_counts().get('Yes', 0) / df['Has Online delivery'].notna().sum()) * 100
print(f"{percentage:.2f}% of restaurants provide online delivery.")

25.66% of restaurants provide online delivery.

In [ ]:
# Difference between number of votes between restaurants which delivers and does not deliver
vote_difference = df[df['Has Online delivery'] == 'Yes']['Votes'].sum() - df[df['Has Online delivery'] == 'No']['Votes'].sum()
print(vote_difference)

-462817

In [ ]:
# Top 10 cuisines served across cities
top_10_cuisines = (df['Cuisines'].dropna().str.split(',').explode().str.strip().value_counts().head(10))
print(top_10_cuisines)

In [ ]:
# Drop missing cuisines
df_clean = df.dropna(subset=['Cuisines'])

# Count number of cuisines per restaurant
df_clean['Cuisine Count'] = df_clean['Cuisines'].str.split(',').apply(len)

# Get max and min
max_cuisines = df_clean['Cuisine Count'].max()
min_cuisines = df_clean['Cuisine Count'].min()

print("Maximum cuisines served by one restaurant:", max_cuisines)
print("Minimum cuisines served by one restaurant:", min_cuisines)

Maximum cuisines served by one restaurant: 8
Minimum cuisines served by one restaurant: 1

/tmp/ipython-input-26-1791442394.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Cuisine Count'] = df_clean['Cuisines'].str.split(',').apply(len)

In [ ]:
df_exploded = df_clean.copy()
df_exploded['Cuisines'] = df_exploded['Cuisines'].str.split(',')
df_exploded = df_exploded.explode('Cuisines')
df_exploded['Cuisines'] = df_exploded['Cuisines'].str.strip()

top_cuisine_per_city = (
    df_exploded.groupby(['City', 'Cuisines'])
    .size()
    .reset_index(name='Count')
    .sort_values(['City', 'Count'], ascending=[True, False])
    .drop_duplicates('City')
)

print(top_cuisine_per_city)

                 City      Cuisines  Count
11          Abu Dhabi        Indian      7
37               Agra  North Indian     15
48          Ahmedabad   Continental     12
62             Albany      American      4
91          Allahabad  North Indian     12
...               ...           ...    ...
1815          Weirton        Burger      1
1820  Wellington City          Cafe      9
1835   Winchester Bay        Burger      1
1838          Yorkton         Asian      1
1842        €¡stanbul          Cafe      4

[140 rows x 3 columns]

In [ ]:
bins = [0, 200, 400, 600, 800, 1000, 2000, df['Average Cost for two'].max()]
labels = ['<200', '200-400', '400-600', '600-800', '800-1000', '1000-2000', '2000+']
df['Cost Range'] = pd.cut(df['Average Cost for two'], bins=bins, labels=labels)

cost_distribution = df['Cost Range'].value_counts().sort_index()
print(cost_distribution)

Cost Range
<200         2117
200-400      2701
400-600      2077
600-800       996
800-1000      467
1000-2000     917
2000+         258
Name: count, dtype: int64

In [ ]:
# Ratings by Online delivery
df.groupby('Has Online delivery')['Aggregate rating'].mean()

Has Online delivery
No     2.465296
Yes    3.248837
Name: Aggregate rating, dtype: float64

In [ ]:
# Ratings by Table booking
df.groupby('Has Table booking')['Aggregate rating'].mean()

Has Table booking
No     2.559359
Yes    3.441969
Name: Aggregate rating, dtype: float64

In [ ]:
# Ratings by City
df.groupby('City')['Aggregate rating'].mean().sort_values(ascending=False)

City
Inner City          4.900000
Quezon City         4.800000
Makati City         4.650000
Pasig City          4.633333
Mandaluyong City    4.625000
                      ...
New Delhi           2.438845
Montville           2.400000
Mc Millan           2.400000
Noida               2.036204
Faridabad           1.866932
Name: Aggregate rating, Length: 141, dtype: float64

In [ ]:
# Ratings by Cuisines (Top 10 Cuisines)
df_cuisine = df.dropna(subset=['Cuisines'])
df_cuisine = df_cuisine.copy()
df_cuisine['Cuisines'] = df_cuisine['Cuisines'].str.split(',')
df_cuisine = df_cuisine.explode('Cuisines')
df_cuisine['Cuisines'] = df_cuisine['Cuisines'].str.strip()
df_cuisine.groupby('Cuisines')['Aggregate rating'].mean().sort_values(ascending=False).head(10)

Cuisines
Sunda         4.900000
BÌ_rek        4.700000
Taiwanese     4.650000
Ramen         4.500000
Dim Sum       4.466667
Hawaiian      4.412500
Bubble Tea    4.400000
DÌ_ner        4.400000
Curry         4.400000
Kebab         4.380000
Name: Aggregate rating, dtype: float64

In [ ]:
# Ratings by Cost range
bins = [0, 200, 400, 600, 800, 1000, 2000, df['Average Cost for two'].max()]
labels = ['<200', '200-400', '400-600', '600-800', '800-1000', '1000-2000', '2000+']
df['Cost Range'] = pd.cut(df['Average Cost for two'], bins=bins, labels=labels)

df.groupby('Cost Range')['Aggregate rating'].mean().sort_index()

/tmp/ipython-input-35-1847908449.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Cost Range')['Aggregate rating'].mean().sort_index()

Cost Range
<200         2.431790
200-400      2.117401
400-600      2.664420
600-800      3.139859
800-1000     3.337045
1000-2000    3.664231
2000+        3.689147
Name: Aggregate rating, dtype: float64